services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    networks:
      - cc-network

  frontend:
    build:
      context: ./ScaledFrontEnd/congestion-frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:8080
    depends_on:
      - backend
    networks:
      - cc-network

  ns3-sim:
    build:
      context: ./ns3_files
      dockerfile: Dockerfile
    ports:
      - "8000-8001:8000" # Maps the new Python Sidecar Manager API
    networks:
      - cc-network
   

 
networks:
  cc-network:
    driver: bridge