def build(bld):
    obj = bld.create_ns3_program(
        'rl-tcp-inference',
        ['sim_inference.cc',
         'tcp-rl-env-inference.cc',
         'tcp-rl-inference.cc']
    )
    obj.source += ['../rl-tcp/tcp-rl.cc', '../rl-tcp/tcp-rl-env.cc']
