def build(bld):
    obj = bld.create_ns3_program('rl-tcp-inference', ['core', 'network', 'internet', 'point-to-point', 'applications'])
    obj.source = 'rl-tcp-inference.cc tcp-rl-env-inference.cc'
    
    # Explicitly include the headers and the source code
    obj.includes = ['/sim/ns-allinone-3.35/ns-3.35/contrib/ns3-ai/model']
    obj.source += ' /sim/ns-allinone-3.35/ns-3.35/contrib/ns3-ai/model/ns3-ai-module.cc'